# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|

  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  # rspec-mocks config goes here. You can use an alternate test double
  # library (such as bogus or mocha) by changing the `mock_with` option here.
  config.mock_with :rspec do |mocks|
    # Prevents you from mocking or stubbing a method that does not exist on
    # a real object. This is generally recommended, and will default to
    # `true` in RSpec 4.
    mocks.verify_partial_doubles = true
  end

  config.shared_context_metadata_behavior = :apply_to_host_groups



  RSpec::Matchers.define :be_the_same_aircraft_as do |expected_aircraft|
    match do |actual_aircraft|
      actual_aircraft.name == expected_aircraft.name &&
      actual_aircraft.cruising_range == expected_aircraft.cruising_range
    end
    failure_message do |actual_aircraft|
      "expected that #{actual_aircraft} would have all the attributes the same as #{expected_monster}. Attributes:\n
      ACTUAL | EXPECTED\n
      #{actual_aircraft.name} | #{expected_aircraft.name}\n
      #{actual_aircraft.cruising_range} | #{expected_aircraft.cruising_range}\n"
    end
  end
end

